/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 3/23/2023 3:30:39 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using SofiForce.DataObjects;
using SofiForce.DataObjects.Interfaces;
using SofiForce.BusinessObjects.Interfaces;

namespace SofiForce.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOPromotionVw.
	///</Summary>
	public partial class BOPromotionVw : zSofiForceConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _promotionId;
		protected string _promotionCode;
		protected Int32? _companyId;
		protected DateTime? _validFrom;
		protected DateTime? _validTo;
		protected bool? _isActive;
		protected Int32? _promotionTypeId;
		protected Int32? _priority;
		protected Int32? _repeats;
		protected string _icon;
		protected string _color;
		protected string _promotionDesc;
		protected Int32? _promotionGroupId;
		protected Int32? _displayOrder;
		protected bool? _enableNotification;
		protected DateTime? _notificationDate;
		protected bool? _notificationDone;
		protected string _promotionTypeCode;
		protected string _promotionTypeNameAr;
		protected string _promotionTypeNameEn;
		protected Int32? _promotionOutputId;
		protected Int32? _promotionInputId;
		protected string _promotionGroupCode;
		protected string _promotionGroupNameEn;
		protected string _promotionGroupNameAr;
		protected string _repeatTypeNameEn;
		protected string _repeatTypeNameAr;
		protected Int32? _repeatTypeId;
		protected bool? _isApproved;
		protected Int32? _promotionCategoryId;
		protected string _vendorCode;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOPromotionVw()
		{
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOPromotionVw
		///</parameters>
		protected internal BOPromotionVw(DAOPromotionVw daoPromotionVw)
		{
			try
			{
				_promotionId = daoPromotionVw.PromotionId;
				_promotionCode = daoPromotionVw.PromotionCode;
				_companyId = daoPromotionVw.CompanyId;
				_validFrom = daoPromotionVw.ValidFrom;
				_validTo = daoPromotionVw.ValidTo;
				_isActive = daoPromotionVw.IsActive;
				_promotionTypeId = daoPromotionVw.PromotionTypeId;
				_priority = daoPromotionVw.Priority;
				_repeats = daoPromotionVw.Repeats;
				_icon = daoPromotionVw.Icon;
				_color = daoPromotionVw.Color;
				_promotionDesc = daoPromotionVw.PromotionDesc;
				_promotionGroupId = daoPromotionVw.PromotionGroupId;
				_displayOrder = daoPromotionVw.DisplayOrder;
				_enableNotification = daoPromotionVw.EnableNotification;
				_notificationDate = daoPromotionVw.NotificationDate;
				_notificationDone = daoPromotionVw.NotificationDone;
				_promotionTypeCode = daoPromotionVw.PromotionTypeCode;
				_promotionTypeNameAr = daoPromotionVw.PromotionTypeNameAr;
				_promotionTypeNameEn = daoPromotionVw.PromotionTypeNameEn;
				_promotionOutputId = daoPromotionVw.PromotionOutputId;
				_promotionInputId = daoPromotionVw.PromotionInputId;
				_promotionGroupCode = daoPromotionVw.PromotionGroupCode;
				_promotionGroupNameEn = daoPromotionVw.PromotionGroupNameEn;
				_promotionGroupNameAr = daoPromotionVw.PromotionGroupNameAr;
				_repeatTypeNameEn = daoPromotionVw.RepeatTypeNameEn;
				_repeatTypeNameAr = daoPromotionVw.RepeatTypeNameAr;
				_repeatTypeId = daoPromotionVw.RepeatTypeId;
				_isApproved = daoPromotionVw.IsApproved;
				_promotionCategoryId = daoPromotionVw.PromotionCategoryId;
				_vendorCode = daoPromotionVw.VendorCode;
			}
			catch
			{
				throw;
			}
		}

		
		///<Summary>
		///PromotionVwCollection
		///This method returns the collection of BOPromotionVw objects
		///</Summary>
		///<returns>
		///List[BOPromotionVw]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOPromotionVw> PromotionVwCollection()
		{
			try
			{
				IList<BOPromotionVw> boPromotionVwCollection = new List<BOPromotionVw>();
				IList<DAOPromotionVw> daoPromotionVwCollection = DAOPromotionVw.SelectAll();
			
				foreach(DAOPromotionVw daoPromotionVw in daoPromotionVwCollection)
					boPromotionVwCollection.Add(new BOPromotionVw(daoPromotionVw));
			
				return boPromotionVwCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///PromotionVwCollectionCount
		///This method returns the collection count of BOPromotionVw objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 PromotionVwCollectionCount()
		{
			try
			{
				Int32 objCount = DAOPromotionVw.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BOPromotionVw>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DAOPromotionVw.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///PromotionVwCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BOPromotionVw objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boPromotionVwCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DAOPromotionVw> daoPromotionVwCollection = DAOPromotionVw.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DAOPromotionVw resdaoPromotionVw in daoPromotionVwCollection)
					boPromotionVwCollection.Add((T)(object)new BOPromotionVw(resdaoPromotionVw));
			
				return boPromotionVwCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///PromotionVwCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BOPromotionVw objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DAOPromotionVw.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? PromotionId
		{
			get
			{
				 return _promotionId;
			}
			set
			{
				_promotionId = value;
				_isDirty = true;
			}
		}
		
		public virtual string PromotionCode
		{
			get
			{
				 return _promotionCode;
			}
			set
			{
				_promotionCode = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? CompanyId
		{
			get
			{
				 return _companyId;
			}
			set
			{
				_companyId = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? ValidFrom
		{
			get
			{
				 return _validFrom;
			}
			set
			{
				_validFrom = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? ValidTo
		{
			get
			{
				 return _validTo;
			}
			set
			{
				_validTo = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? IsActive
		{
			get
			{
				 return _isActive;
			}
			set
			{
				_isActive = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? PromotionTypeId
		{
			get
			{
				 return _promotionTypeId;
			}
			set
			{
				_promotionTypeId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Priority
		{
			get
			{
				 return _priority;
			}
			set
			{
				_priority = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Repeats
		{
			get
			{
				 return _repeats;
			}
			set
			{
				_repeats = value;
				_isDirty = true;
			}
		}
		
		public virtual string Icon
		{
			get
			{
				 return _icon;
			}
			set
			{
				_icon = value;
				_isDirty = true;
			}
		}
		
		public virtual string Color
		{
			get
			{
				 return _color;
			}
			set
			{
				_color = value;
				_isDirty = true;
			}
		}
		
		public virtual string PromotionDesc
		{
			get
			{
				 return _promotionDesc;
			}
			set
			{
				_promotionDesc = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? PromotionGroupId
		{
			get
			{
				 return _promotionGroupId;
			}
			set
			{
				_promotionGroupId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? DisplayOrder
		{
			get
			{
				 return _displayOrder;
			}
			set
			{
				_displayOrder = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? EnableNotification
		{
			get
			{
				 return _enableNotification;
			}
			set
			{
				_enableNotification = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? NotificationDate
		{
			get
			{
				 return _notificationDate;
			}
			set
			{
				_notificationDate = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? NotificationDone
		{
			get
			{
				 return _notificationDone;
			}
			set
			{
				_notificationDone = value;
				_isDirty = true;
			}
		}
		
		public virtual string PromotionTypeCode
		{
			get
			{
				 return _promotionTypeCode;
			}
			set
			{
				_promotionTypeCode = value;
				_isDirty = true;
			}
		}
		
		public virtual string PromotionTypeNameAr
		{
			get
			{
				 return _promotionTypeNameAr;
			}
			set
			{
				_promotionTypeNameAr = value;
				_isDirty = true;
			}
		}
		
		public virtual string PromotionTypeNameEn
		{
			get
			{
				 return _promotionTypeNameEn;
			}
			set
			{
				_promotionTypeNameEn = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? PromotionOutputId
		{
			get
			{
				 return _promotionOutputId;
			}
			set
			{
				_promotionOutputId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? PromotionInputId
		{
			get
			{
				 return _promotionInputId;
			}
			set
			{
				_promotionInputId = value;
				_isDirty = true;
			}
		}
		
		public virtual string PromotionGroupCode
		{
			get
			{
				 return _promotionGroupCode;
			}
			set
			{
				_promotionGroupCode = value;
				_isDirty = true;
			}
		}
		
		public virtual string PromotionGroupNameEn
		{
			get
			{
				 return _promotionGroupNameEn;
			}
			set
			{
				_promotionGroupNameEn = value;
				_isDirty = true;
			}
		}
		
		public virtual string PromotionGroupNameAr
		{
			get
			{
				 return _promotionGroupNameAr;
			}
			set
			{
				_promotionGroupNameAr = value;
				_isDirty = true;
			}
		}
		
		public virtual string RepeatTypeNameEn
		{
			get
			{
				 return _repeatTypeNameEn;
			}
			set
			{
				_repeatTypeNameEn = value;
				_isDirty = true;
			}
		}
		
		public virtual string RepeatTypeNameAr
		{
			get
			{
				 return _repeatTypeNameAr;
			}
			set
			{
				_repeatTypeNameAr = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? RepeatTypeId
		{
			get
			{
				 return _repeatTypeId;
			}
			set
			{
				_repeatTypeId = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? IsApproved
		{
			get
			{
				 return _isApproved;
			}
			set
			{
				_isApproved = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? PromotionCategoryId
		{
			get
			{
				 return _promotionCategoryId;
			}
			set
			{
				_promotionCategoryId = value;
				_isDirty = true;
			}
		}
		
		public virtual string VendorCode
		{
			get
			{
				 return _vendorCode;
			}
			set
			{
				_vendorCode = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
