/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 9/9/2023 5:10:24 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using SofiForce.DataObjects;
using SofiForce.DataObjects.Interfaces;
using SofiForce.BusinessObjects.Interfaces;

namespace SofiForce.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOSalesOrderError.
	///</Summary>
	public partial class BOSalesOrderError : zSofiForceConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int64? _errorId;
		protected Int64? _salesId;
		protected string _errorDetail;
		protected DateTime? _errorDate;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOSalesOrderError()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int64 errorId
		///</parameters>
		public BOSalesOrderError(Int64 errorId)
		{
			try
			{
				DAOSalesOrderError daoSalesOrderError = DAOSalesOrderError.SelectOne(errorId);
				_errorId = daoSalesOrderError.ErrorId;
				_salesId = daoSalesOrderError.SalesId;
				_errorDetail = daoSalesOrderError.ErrorDetail;
				_errorDate = daoSalesOrderError.ErrorDate;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOSalesOrderError
		///</parameters>
		protected internal BOSalesOrderError(DAOSalesOrderError daoSalesOrderError)
		{
			try
			{
				_errorId = daoSalesOrderError.ErrorId;
				_salesId = daoSalesOrderError.SalesId;
				_errorDetail = daoSalesOrderError.ErrorDetail;
				_errorDate = daoSalesOrderError.ErrorDate;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new SalesOrderError record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOSalesOrderError daoSalesOrderError = new DAOSalesOrderError();
			RegisterDataObject(daoSalesOrderError);
			BeginTransaction("savenewBOSalesOrderError");
			try
			{
				daoSalesOrderError.SalesId = _salesId;
				daoSalesOrderError.ErrorDetail = _errorDetail;
				daoSalesOrderError.ErrorDate = _errorDate;
				daoSalesOrderError.Insert();
				CommitTransaction();
				
				_errorId = daoSalesOrderError.ErrorId;
				_salesId = daoSalesOrderError.SalesId;
				_errorDetail = daoSalesOrderError.ErrorDetail;
				_errorDate = daoSalesOrderError.ErrorDate;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBOSalesOrderError");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one SalesOrderError record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOSalesOrderError
		///</parameters>
		public virtual void Update()
		{
			DAOSalesOrderError daoSalesOrderError = new DAOSalesOrderError();
			RegisterDataObject(daoSalesOrderError);
			BeginTransaction("updateBOSalesOrderError");
			try
			{
				daoSalesOrderError.ErrorId = _errorId;
				daoSalesOrderError.SalesId = _salesId;
				daoSalesOrderError.ErrorDetail = _errorDetail;
				daoSalesOrderError.ErrorDate = _errorDate;
				daoSalesOrderError.Update();
				CommitTransaction();
				
				_errorId = daoSalesOrderError.ErrorId;
				_salesId = daoSalesOrderError.SalesId;
				_errorDetail = daoSalesOrderError.ErrorDetail;
				_errorDate = daoSalesOrderError.ErrorDate;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBOSalesOrderError");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one SalesOrderError record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOSalesOrderError daoSalesOrderError = new DAOSalesOrderError();
			RegisterDataObject(daoSalesOrderError);
			BeginTransaction("deleteBOSalesOrderError");
			try
			{
				daoSalesOrderError.ErrorId = _errorId;
				daoSalesOrderError.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBOSalesOrderError");
				throw;
			}
		}
		
		///<Summary>
		///SalesOrderErrorCollection
		///This method returns the collection of BOSalesOrderError objects
		///</Summary>
		///<returns>
		///List[BOSalesOrderError]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOSalesOrderError> SalesOrderErrorCollection()
		{
			try
			{
				IList<BOSalesOrderError> boSalesOrderErrorCollection = new List<BOSalesOrderError>();
				IList<DAOSalesOrderError> daoSalesOrderErrorCollection = DAOSalesOrderError.SelectAll();
			
				foreach(DAOSalesOrderError daoSalesOrderError in daoSalesOrderErrorCollection)
					boSalesOrderErrorCollection.Add(new BOSalesOrderError(daoSalesOrderError));
			
				return boSalesOrderErrorCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///SalesOrderErrorCollectionCount
		///This method returns the collection count of BOSalesOrderError objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SalesOrderErrorCollectionCount()
		{
			try
			{
				Int32 objCount = DAOSalesOrderError.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BOSalesOrderError>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DAOSalesOrderError.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///SalesOrderErrorCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BOSalesOrderError objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boSalesOrderErrorCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DAOSalesOrderError> daoSalesOrderErrorCollection = DAOSalesOrderError.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DAOSalesOrderError resdaoSalesOrderError in daoSalesOrderErrorCollection)
					boSalesOrderErrorCollection.Add((T)(object)new BOSalesOrderError(resdaoSalesOrderError));
			
				return boSalesOrderErrorCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///SalesOrderErrorCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BOSalesOrderError objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DAOSalesOrderError.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int64? ErrorId
		{
			get
			{
				 return _errorId;
			}
			set
			{
				_errorId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int64? SalesId
		{
			get
			{
				 return _salesId;
			}
			set
			{
				_salesId = value;
				_isDirty = true;
			}
		}
		
		public virtual string ErrorDetail
		{
			get
			{
				 return _errorDetail;
			}
			set
			{
				_errorDetail = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? ErrorDate
		{
			get
			{
				 return _errorDate;
			}
			set
			{
				_errorDate = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
