export class ClientListModel {
    clientCode: string;
    clientName: string;
    branchId: number | null;
    branchName: string;
    branchCode: string;
    creditLimit: number | null;
    creditBalance: number | null;
    phone: string;
    mobile: string;
    whatsApp: string;
    isActive: boolean | null;
    clientId: number | null;
    clientTypeName: string;
    clientTypeId: number | null;
    clientAccountId: number | null;
    regionId: number | null;
    governerateId: number | null;
    cityId: number | null;
    clientGroupId: number | null;
    clientGroupSubId: number | null;
    clientClassificationId: number | null;
    paymentTermId: number | null;
    paymentTermName:string;
    isTaxable: boolean | null;
    longitude: number | null;
    latitude: number | null;
    governerateName: string;
    cityName: string;
    taxCode: string;
    commercialCode: string;
    isChain: boolean | null;
    locationLevelId: number | null;
    clientGroupSubCode: string;
    clientGroupSubName: string;
    clientGroupCode: string;
    clientGroupName: string;
    isNew: boolean | null;
    needValidation: boolean | null;
    businessUnitCode: string;
    businessUnitName: string;
    businessUnitId: number | null;
    isCashDiscount: boolean | null;
    inRoute: boolean | null;
    cashGroupId: number | null;
    governerateCode: string;
    cityCode: string;
}